### ISSUE TITLE
Updating code for new params.csv file

### ISSUE THREAD

**Issue by clchand23** [EpiModel/EpiModelHIV-Template#41]
Hi @AdrienLeGuillou - I think some of the setup `00-setup.R` and `netsim_settings.R` code need to be updated to reflect the new `params.csv` file. 

Pulling in the `model_parameters.xslx` file may be deleted from here:
https://github.com/EpiModel/EpiModelHIV-Template/blob/6616fc72fa1042d52652235e63d6036d4159aae9/R/00-setup.R#L18C1-L22C2

Update code in `netsim_settings.R` to read `params.csv` file
https://github.com/EpiModel/EpiModelHIV-Template/blob/6616fc72fa1042d52652235e63d6036d4159aae9/R/netsim_settings.R#L11C1-L12C36

I used this:
```r
params_df <- read.csv(fs::path(input_dir, "params.csv")) |>
  dplyr::select(param, value, type)
```

**Comment by AdrienLeGuillou** [comment]
I updated it in the dev branch.
The current main branch here gets EpiModel 3.1.x. When EpiModel 2.5 is released on CRAN, I will update EMHIVp and the template as well with all the changes

**Comment by clchand23** [comment]
I see - thanks! Should I be using the main or dev branch for my project repo?

**Comment by AdrienLeGuillou** [comment]
If it's a new project I would say the dev one. 
Just give me 30 mins to make sure it is in a working state ^^

**Comment by AdrienLeGuillou** [comment]
This would be for a new project?
How much code from a previous one do you intend to re-use?

**Comment by clchand23** [comment]
I just created it yesterday, so it's completely new and am starting from scratch. I am using the EpiModelHIV-p v3.1.x branch for my software repo.

**Comment by AdrienLeGuillou** [comment]
See my msg on slack, closing here
